### ISSUE TITLE
Test project templates use latest C# language idioms

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/test-templates#164]
In .NET 6, the included C# project templates will use the latest language idioms.

See the [parent Epic](https://github.com/dotnet/templating/issues/3359) for details.

@kendrahavens

**Comment by Sanan07** [comment]
@DamianEdwards  Should we add all mentioned features to our template? For instance, we do not have `Program.cs` file in our test template. 
I assume only some of them applied in our case.

**Comment by Haplois** [comment]
@Sanan07, we cannot apply bellow yet:
 * [Top-level statements][top-level-statements]: The Test Platform has a bug which prevents tests declared in a class without a namespace to be run. [See: #microsoft/testfx/issues/889] 
 * [async Main][async-main]: We generally don't have an entry point in our tests.

These can be considered:
* [Global using directives][global-using]
* [File-scoped namespaces][file-scoped]
* [Nullable reference types][nullable-ref]

// cc: @nohwnd 

[top-level-statements]: https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements
[async-main]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.1/async-main
[global-using]: https://github.com/dotnet/csharplang/issues/3428
[file-scoped]: https://github.com/dotnet/csharplang/issues/137
[nullable-ref]: https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references

**Comment by DamianEdwards** [comment]
Thanks @Haplois. Yes the intent is to make only those changes that are applicable and to follow up on any issues that are preventing a change that could be made, being made.

**Comment by Haplois** [comment]
File-scoped namespaces are blocked by https://github.com/dotnet/roslyn/pull/54763.

**Comment by DamianEdwards** [comment]
@Haplois this should be unblocked now as of the latest SDK builds for preview.7 from main

**Comment by Haplois** [comment]
@DamianEdwards, thanks.
