### ISSUE TITLE
Update nunit-test item template to latest lang idioms

### ISSUE THREAD

**Issue by nohwnd** [dotnet/test-templates#169]
NUnit is the only item template we have, unlike the others which are project templates. Item templates don't get additional info like TFM, so using newest features in them, like file level namespaces, can't be done because the latest template is always used, and we have nothing to switch on. 

This is a known limitation of `dotnet new` and is tracked here: https://github.com/dotnet/templating/issues/338

Updating the template was attempted here, but was rolled back: https://github.com/dotnet/test-templates/pull/168

**Comment by Haplois** [comment]
Background info #164

**Comment by nohwnd** [comment]
@cvpoienaru  @Evangelink (and @Haplois ) this was fixed if you want to fix it in net8. Docs are here:  https://github.com/dotnet/templating/pull/5148
