### ISSUE TITLE
Consider adding an xunit.runner.json to xunit projects

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/test-templates#2]
_From @rynowak on April 28, 2017 1:55_

There's a bunch of useful settings for xunit that are only configurable via the `xunit.runner.json` file, but it's not very discoverable. See https://xunit.github.io/docs/configuring-with-json.html

We should think about including this in the templates.

This has come up many times for projects that test ASP.NET MVC and it usually looks something like this: https://github.com/aspnet/Razor/issues/1212#issuecomment-297885722 The common case for us is that we need to disable shadow copy.

_Copied from original issue: dotnet/templating#704_

**Comment by nohwnd** [comment]
This seems like the responsibility of the xunit package. It can add the file via tools in the nuget package if the authors of xunit wish to do it. We could add a default file to be helpful, but that would force us to track braking changes, and the shipping cadence is not huge for templates. So I would rather keep it the default and avoided adding this file.
