### ISSUE TITLE
Update package references in testing project templates to Microsoft.NET.Test.Sdk to 17.0.0

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/test-templates#200]
Seems this was missed as part of the .NET 6/VS 17.0 release.

**Comment by Sanan07** [comment]
Updated by #206.

**Comment by OsirisTerje** [comment]
When will this be out?  

Or, more general - what is the release schedule of these templates?  Do they follow VS releases or do they follow dotnet releases ?

**Comment by DamianEdwards** [comment]
@Sanan07 can we back-port this change to the 6.0.200 or 6.0.300 SDK release?

**Comment by OsirisTerje** [comment]
@Sanan07 @DamianEdwards Did backporting happen?
