### ISSUE TITLE
readme.md documentation for contributing is confusing

### ISSUE THREAD

**Issue by qayshp** [dotnet/test-templates#210]
Quite minor in all ways, but the documentation on this is unclear and confusing. I would propose a change but don't know what the desired intent would be.

https://github.com/dotnet/test-templates/blob/f5f8cf4b2e3234428730e64162af51abd67551fe/README.md?plain=1#L31-L32
specifies to use the default branch instead of `main` for contributions, but `main` _is_ the default branch for this repository.

**Comment by Sanan07** [comment]
Instead of default it should be : your feature branch in forked repo
