### ISSUE TITLE
Unified Build control update

### ISSUE THREAD

**Issue by mmitche** [dotnet/test-templates#246]
### Description

**This issue is dependent on https://github.com/dotnet/source-build/issues/2974 and is a placeholder for .NET 8 required work in product repositories.**

Instructions for implementation will be updated once https://github.com/dotnet/source-build/issues/2974 but will likely be a mechanical shift of properties in this repo. In a general sense, this is scaffolding work for expanding the set of source-built platforms beyond Linux.

**Comment by mmitche** [comment]
This is .NET 8 work

**Comment by Evangelink** [comment]
@mmitche Is there any work required from us here or is it fully handled by source-build team/group?

**Comment by mmitche** [comment]
@Evangelink Unknown at the moment. Still in progress. A design has just recently been completed.

**Comment by mmitche** [comment]
Merged
