### ISSUE TITLE
TargetFramework in package projects is blocking TFM trimming work in source-build

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/test-templates#292]
Packaging projects, have `TargetFramework` set to `netstandard1.0` - i.e.: https://github.com/dotnet/test-templates/blob/eb937b61acd09d5698e9c16d80e2ad49f4eeaada/template_feed/Microsoft.DotNet.Test.ProjectTemplates.8.0/Microsoft.DotNet.Test.ProjectTemplates.8.0.csproj#L3

This is blocking TFM trimming work for source-build: https://github.com/dotnet/test-templates/issues/248

Can we update `TargetFramework` to `netstandard2.0`, which is the lowest allowed TFM for the trimming work.

These packages do not appear on nuget.org, and they might just be used as transport packages. So it seems that we should be able to update `TargetFramework` without any impact to consumers.

**Comment by NikolaMilosavljevic** [comment]
@mmitche

**Comment by NikolaMilosavljevic** [comment]
@dotnet/dotnet-test-templates-admin

**Comment by MarcoRossignoli** [comment]
@cvpoienaru can you fix it?

**Comment by NikolaMilosavljevic** [comment]
@nohwnd @MarcoRossignoli @ManishJayaswal @Evangelink @pavelhorak
