### ISSUE TITLE
XUnit templates refers coverlet which is not compatible with WPF projects

### ISSUE THREAD

**Issue by lg2de** [dotnet/test-templates#296]
The default template for XUnit projects (maybe also for other test frameworks) references the project `coverlet.collector`.
Coverlet is currently not compatible with projects with WPF option. Testing WPF projects with Coverlet, the coverage fails with 

> Unable to instrument module: ***\Module.dll because : AssemblyResolutionException for 'PresentationFramework, Version=***

I've two questions:
1. Are you aware about the incompatibility of the default template with WPF projects?
2. With coverlet-coverage/coverlet#1449 I tried already to fix the problem, but the feedback is as slow as the whole project in my eyes. Is this the best selection for the default template of the .NET SDK?

**Comment by fhnaseer** [comment]
MS Code coverage should work fine with WPF projects.

**Comment by Evangelink** [comment]
@lg2de Have you been able to make some progresses?

**Comment by lg2de** [comment]
The bug is fixed, but the release is pending for long time.

**Comment by Evangelink** [comment]
@lg2de which release (release of which tool/product) are you referring to?

**Comment by lg2de** [comment]
The release of `coverlet` is missing. So, there is still no release of `coverlet` available which can be used to test WPF projects.
My fix was merged in July '23, the last release was created in May '23.

**Comment by lg2de** [comment]
This looks really cool, @cremor.
I myself already switched (back) to MS coverage. I stopped waiting for a release of my fix... :(
Maybe dotnet templates can also switch.

**Comment by Evangelink** [comment]
This is a tricky topic :) This is not always well received when the templates are suggesting MS tools instead of OSS ones.

@lg2de Would you mind linking your coverlet issue here?

I'll move forward by closing this issue as there is nothing specific for us to do here. We will update coverlet version when we know a new version is available.

**Comment by lg2de** [comment]
The PR is already linked in the initial message.
