### ISSUE TITLE
Use project configuration instead of class

### ISSUE THREAD

**Issue by Varorbc** [dotnet/test-templates#306]
@Evangelink 

### use
```
<ItemGroup>
  <Using Include="Xunit" />
</ItemGroup>
```
### instead of
```
global using Xunit;
```

**Comment by Evangelink** [comment]
Thanks for the suggestion @Varorbc! We will review it and get back to you (I wasn't aware of this syntax so thanks for the learning :)).

**Comment by Evangelink** [comment]
@Varorbc Sure please go ahead! Please update only net9 folder https://github.com/dotnet/test-templates/tree/main/template_feed/Microsoft.DotNet.Test.ProjectTemplates.9.0, I will double check with the team if we can ship such change in already shipped .NET versions.

Also, if you are willing to, please do the same pattern for NUnit and MSTest templates.
