### ISSUE TITLE
Update test dependencies for VS templates

### ISSUE THREAD

**Issue by timheuer** [dotnet/test-templates#388]
Can we take an update on templates to update the following dependencies:

- [ ] Coverlet to 6.0.2
- [ ] Microsoft.NET.Test.Sdk to 17.9.0
- [ ] MSTest.TestAdapter to 3.3.1
- [ ] MSTest.TestFramework to 3.3.1
- [ ] NUnit to 4.1.0
- [ ] NUnit.Analyzers to 4.2.0
- [ ] xunit to 2.7.1
- [ ] xunit.runner.visualstudio to 2.5.8

**Comment by AbhitejJohn** [comment]
@pavelhorak , @Evangelink : Reaching out since we weren't sure this is the right repo for this issue - would be grateful if you could help move if needed.

**Comment by Evangelink** [comment]
@timheuer VS templates are using what is shipped inside the SDK so versions depends on the available SDK. MSTest has some special templates for which we cannot bump to v3+ because we dropped support for TFMs < net462 but VS still allows to target these so it would not work.

**Comment by timheuer** [comment]
Thanks @Evangelink -- I think we should think of perhaps what is the better experience. for 'new' here -- is it getting a warning that you have already out-dated packages after creating a NEW test project? or is it better to have those who re-target to others discover they need to down-grade?

I'm not sure the answer, but I think the 'new' experience I'm seeing is that it looks like we're not keeping up with stable..that's the perception I had.

**Comment by cremor** [comment]
> MSTest has some special templates for which we cannot bump to v3+ because we dropped support for TFMs < net462 but VS still allows to target these so it would not work.

But .NET Framework templates are separate anyway. They use the legacy csproj format.
Couldn't all current .NET (SDK style csproj) templates be updated?

> * MSTest.TestAdapter to 3.3.1
> * MSTest.TestFramework to 3.3.1

Instead of updating those separately the "MSTest" meta package should be referenced. Starting with 3.2.0 this also brings in "MSTest.Analyzers". Additionally, it also brings "Microsoft.NET.Test.Sdk" so that direct reference could be removed.

Note: I see that the main branch of this repository already moved to the MSTest SDK, which does this implicitly. But as far as I can see this only applies to .NET 9 templates. The templates for older .NET versions could still be updated.

**Comment by Evangelink** [comment]
> But .NET Framework templates are separate anyway. They use the legacy csproj format.
> Couldn't all current .NET (SDK style csproj) templates be updated?

Sadly not, MSTest v3 only supports .NET 4.6.2+ (supported runtime versions) while VS still needs to support older versions so we cannot update those templates to newer versions. 
I did try to implement a wizard that would allow to switch version based on target framework but I wasn't so successful. I could try to ping some VS experts to get some help.

> The templates for older .NET versions could still be updated.

Another point that seems easy from the outside but isn't in practice. Test templates are inserted into the various versions of .NET SDK. Based on the SDK you target, the template of the respective SDK will be used (you can make a quick test by creating a MSTest project targeting net6.0 and net8.0 - you will see different templates/versions of the packages). For us to be able to patch old SDKs, this means going through a "patching request" path and adding features/bumping versions would not meet the bar of value vs risk.

**Comment by cremor** [comment]
> Sadly not, MSTest v3 only supports .NET 4.6.2+ (supported runtime versions) while VS still needs to support older versions so we cannot update those templates to newer versions.
> I did try to implement a wizard that would allow to switch version based on target framework but I wasn't so successful. I could try to ping some VS experts to get some help.

I don't understand. If I create two new MSTest projects right now in Visual Studio, one targeting .NET Framework and one .NET 8, I already get different MSTest versions.
If I create an unit test project for .NET Framework I get a legacy style csproj with a reference to MSTest 2.2.10.
But if I create an MSTest project for .NET 8 I get an SDK style csproj with a reference to MSTest 3.1.1.

So there a clearly already two different templates that target two different versions of MSTest. You can't update the one for .NET Framework, ok. But the template using an SDK style csproj file is never used for .NET Framework targeting templates, so it could be updated. And it is already using MSTest v3.

> For us to be able to patch old SDKs, this means going through a "patching request" path and adding features/bumping versions would not meet the bar of value vs risk.

Then I don't understand this issue. If no template changes for existing major .NET versions can be shipped (easily), then many of the points in the initial comment of this issue are already done (in the templates for .NET 9).

**Comment by Evangelink** [comment]
> So there a clearly already two different templates that target two different versions of MSTest. You can't update the one for .NET Framework, ok. But the template using an SDK style csproj file is never used for .NET Framework targeting templates, so it could be updated. And it is already using MSTest v3.

Yes sorry I wasn't clear. So we have 2 kind of templates, solely VS templates (can be found here https://github.com/dotnet/test-templates/tree/main/Templates) and .NET SDK templates (found here https://github.com/dotnet/test-templates/tree/main/template_feed). The .NET SDK templates will also appear in VS but the VS templates won't appear anywhere else.

Now focusing on .NET SDK templates. Depending on the target framework you select during the template creation wizard, you will end up with different project created (not only the target framework but the full project template).

For example, targeting `netcoreapp3.1` you have:
![image](https://github.com/dotnet/test-templates/assets/11340282/0de142d3-0a85-4b69-ada2-c3feea2e4dd0)

Targeting `net6.0` you have:
![image](https://github.com/dotnet/test-templates/assets/11340282/60c889c6-2bc3-4e55-828d-403f7c87ebc2)

Targeting `net8.0` you have:
![image](https://github.com/dotnet/test-templates/assets/11340282/a31956dd-68ef-4d6e-8309-b76a20756c3b)

> Then I don't understand this issue. If no template changes for existing major .NET versions can be shipped (easily), then many of the points in the initial comment of this issue are already done (in the templates for .NET 9).

It's exactly what I am trying to convey but failed to do :)

**Comment by Evangelink** [comment]
@timheuer I'll move forward by closing this issue. Please let me know if you would like for me to schedule a meeting with you and Wendy so we could discuss broader strategy.
