### ISSUE TITLE
Does setting IsPackable still work?

### ISSUE THREAD

**Issue by Varorbc** [dotnet/test-templates#389]
Does setting IsPackable still work?

https://github.com/dotnet/test-templates/blob/31ab6a2d0e3b19f17c4126c859564ccc3a0cae94/template_feed/Microsoft.DotNet.Test.ProjectTemplates.9.0/content/MSTest-CSharp/Company.TestProject1.csproj#L10

I found that the default value [here ](https://github.com/microsoft/testfx/blob/791ab17e27450c5c6f31d63cbceb0784e8099b12/src/Package/MSTest.Sdk/Sdk/Runner/Common.targets#L5) is false

**Comment by Evangelink** [comment]
When using `MSTest.Sdk` we set it to false by default. The props of the SDK will be resolved first and could be overriden by the local (what you are showing here) which would be present if and only if the user is passing the `EnablePack` option when creating the template.

**Comment by Evangelink** [comment]
I am not suprised for the `PreBuildEvent` but yeah that's weird for the `PostBuildEvent`.

Reopening to investigate. Thanks @Varorbc

**Comment by Evangelink** [comment]
@Varorbc are you packing your test project(s)? If so, would you mind me asking what's the purpose?
