### ISSUE TITLE
remove duplicate settings

### ISSUE THREAD

**Issue by Varorbc** [dotnet/test-templates#390]
https://github.com/dotnet/test-templates/blob/31ab6a2d0e3b19f17c4126c859564ccc3a0cae94/template_feed/Microsoft.DotNet.Test.ProjectTemplates.9.0/content/XUnit-CSharp/Company.TestProject1.csproj#L12

https://github.com/dotnet/test-templates/blob/31ab6a2d0e3b19f17c4126c859564ccc3a0cae94/template_feed/Microsoft.DotNet.Test.ProjectTemplates.9.0/content/NUnit-CSharp/Company.TestProject1.csproj#L12

I found that the default value [here ](https://github.com/microsoft/vstest/blob/65d9344b73c9cec20b4f42fc27e6d9ace5ca3c1c/src/package/Microsoft.NET.Test.Sdk/Microsoft.NET.Test.Sdk.props#L17) is true

**Comment by nohwnd** [comment]
That default value is applicable only to projects that install Microsoft.NET.Test.SDK, which is not mandatory for .NET Framework test projects. It is still recommended though. Luckily xunit also sets this property in their props: https://github.com/xunit/xunit/blob/main/src/xunit.v3.core/Package/build/xunit.v3.core.props#L12 , so I don't see a reason to not make this change.

**Comment by Evangelink** [comment]
I just checked and NUnit doesn't so we can only remove it for xUnit. @Varorbc would you be willing to do a PR?

**Comment by nohwnd** [comment]
Valid point.
