### ISSUE TITLE
disable runner does not work

### ISSUE THREAD

**Issue by nohwnd** [dotnet/test-templates#403]
`--disable-runner` option is not respected by mstest template, and I have hard time creating a project that does not use runner, or does not use sdk. E.g. when reproducing issues that happen on .NET Framework, or when I want to easily substitute versions of dependencies without remembering all the package names.

**Comment by Evangelink** [comment]
Thanks @nohwnd! Have you been able to have a quick investigation at what's wrong?

**Comment by Evangelink** [comment]
Ah yeah right sorry I have been on all fronts and didn't pay attention to the global consistency! The template should change `--disable-runner` into `--use-vstest` and set `UseVSTest` property to true (see https://github.com/microsoft/testfx/blob/main/src/Package/MSTest.Sdk/Sdk/Sdk.targets#L8)
