### ISSUE TITLE
Playwright template content overwriting default template in VS 17.12.0 Preview 4?

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/test-templates#510]
Poking around the template configs in `main`, I can't see how this is happening; as there are two separate templates, [the default one](https://github.com/dotnet/test-templates/blob/main/template_feed/Microsoft.DotNet.Test.ProjectTemplates.9.0/content/MSTest-CSharp/.template.config/template.json) and the [playwright one](https://github.com/dotnet/test-templates/blob/main/template_feed/Microsoft.DotNet.Test.ProjectTemplates.9.0/content/Playwright-MSTest-CSharp/.template.config/template.json).

But in VS 17.12.0 Preview 4, I see a weird amalgamation of the two templates:

![Image](https://github.com/user-attachments/assets/a50dda48-b2ab-41c6-ba72-4220e09905af)

This has the default template's _name and description_, but the playwright tags and **_CONTENT_**... (the content being incorrect is the big issue here as it makes it hard to just get started with a basic .NET unit test.) It the only basic 'MSTest' template I see.

Compared to VS 17.11.5 (which still works as expected):

![Image](https://github.com/user-attachments/assets/b692699f-1f5b-4372-b5ed-aea4d3c7f563)

Is this a known issue with VS preview? Is there a way I can tell it to grab the latest feed with this repos content to get the basic blank template?

I need to use VS Preview for a .NET Conf demo recording (**on 10/30**), but we need to create the basic Unit Test template...

**Comment by michael-hawker** [comment]
Update here, I updated to Preview 5 and saw the same issue. However, if I _completely uninstalled_ VS Preview and then re-installed it, then I got more templates back finally.

However, the Playwright template still should as having the wrong name, and they both don't have the test beaker icon as one would expect:
![Image](https://github.com/user-attachments/assets/f8f55ae3-1e80-446f-8680-84ac7296bf19)
![Image](https://github.com/user-attachments/assets/edd293ef-bbd5-4678-bb86-09627de75858)

Selecting the first template works as expected for the content generated. So, still not quite sure what's going on here.

I had someone else who had Preview 3 look at what they had, and they saw a similar result as I see on a fresh install above:
![Image](https://github.com/user-attachments/assets/8ad8ccd2-c0fb-4859-91e8-ba97d5539d24)


I installed only the following workloads:
![Image](https://github.com/user-attachments/assets/256ddac8-bc51-460b-9bfa-a5d34731ad6c)


```
I:\code>dotnet --version
9.0.100-rc.2.24474.11
 
I:\code>dotnet --list-sdks
8.0.403 [C:\Program Files\dotnet\sdk]
9.0.100-rc.2.24474.11 [C:\Program Files\dotnet\sdk]
```

And then I also have VS 17.11.5 installed as my stable build of VS.

**Comment by Evangelink** [comment]
I have checked on 4 different machines and it's working fine for all of them so not sure what's going on.

**Comment by michael-hawker** [comment]
@Evangelink were those fresh installs or updates? Wonder if it's an in-place upgrade issue vs. fresh install? As I did see improvements when I uninstalled the preview vs. updating/restore.

**Comment by Evangelink** [comment]
I need to double check but it was most likely mainly updates and not fresh install. Although we had some vendors validation on that scenario too.

**Comment by Evangelink** [comment]
@michael-hawker are you still seeing issues now?

**Comment by Evangelink** [comment]
Closing as stale.
