### ISSUE TITLE
TUnit template

### ISSUE THREAD

**Issue by thomhurst** [dotnet/test-templates#518]
Would you be willing to support a TUnit template in the future?

**Comment by Evangelink** [comment]
Hi @thomhurst,

Technically yes but I want to get approval from the PMs and team leads in SDK and VS as the templates gets inserted there and it is then leading to many support stories. I'll share the results of the discussion here once I have it.

**Comment by Evangelink** [comment]
Hi @thomhurst,

I just got the answer and we don't want to be supporting other test frameworks (as in owned and managed by us). xUnit and NUnit have been added a long time ago and supporting them is already causing some issues.

I'll move ahead and close as won't fix. I know that xUnit is also shipping its own set of templates directly from his repo, you should consider doing the same.
