### ISSUE TITLE
Warning when first building .Net Core 2.1 F# mstest/xunit/nunit projects

### ISSUE THREAD

**Issue by Jepson112** [dotnet/test-templates#89]
**Steps to reproduce**
1.Install .NET Core SDK: 2.1.807(runtime 2.1.19)
2.Open terminal, Create F# .net core mstest/xunit/nunit projects 
3.Run "dotnet build"

**Expected behavior**
dotnet build succeeded with no Warning.

**Actual behavior**
dotnet build succeeded with  Warning
"/Users/e2euser/.nuget/packages/microsoft.net.test.sdk/15.9.0/build/netcoreapp1.0/Microsoft.Net.Test.Sdk.targets(104,5): warning : A 'Program.fs' file can be automatically generated for F# .NET Core test projects. To fix this warning, either delete the file from the project, or set the <GenerateProgramFile> property to 'false'. [/Users/e2euser/oo/ms1/ms1.fsproj]"
![image](https://user-images.githubusercontent.com/61412494/82972903-b1b78b80-a008-11ea-93aa-a7efe3eeaffa.png)

**Note:**
1.If run "dotnet build" again ,this bug will not report 

**Environment data**
dotnet --info output:
.NET Core SDK (reflecting any global.json):
Version: 3.0.100-preview7-012621​
Commit: 629a4be4f6​
​
Runtime Environment:​
.NET Core SDK (reflecting any global.json):
 Version:   2.1.807
 Commit:    950d0c51b5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.807/

Host (useful for support):
  Version: 2.1.19
  Commit:  6c78987f00

.NET Core SDKs installed:
  2.1.807 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by nohwnd** [comment]
Please refer to: https://github.com/dotnet/test-templates/issues/11
